# Server config
hostname: localhost
port: 3000

# DB config
# Choose either Windows or Linux
OS: Linux
db_server: localhost
db_name: IEgypt_78
# Linux settings
db_username: SA
db_password: Password1
db_port: 1433
