# Server config
hostname: localhost
port: 3000

# DB config
# Choose either Windows or Linux
OS: windows
db_server: DESKTOP-KNPB2R3\SQLEXPRESS
db_name: IEgypt_78
# NOT Linux settings
db_username: SA
db_password: Password1
db_port: 1433
db_driver: {ODBC Driver 17 for SQL Server}
